### ISSUE TITLE
YASH not working with VS code for me

### ISSUE THREAD

**Issue by ajain-02** [babyraging/yash#10] opened 2021-01-30 18:58 UTC
Hello,

I am trying to edit a Lexer.lex file which is shown attached. I have installed YASH extension and yet none of the syntax highlighting or autocompletion options come up. VS code almost treats my file like a .txt file, with no syntax highlighting or auto-completion, even with YASH installed. I have included proof that I have installed YASH extension, and yet still nothing happens.

![Capture1](https://user-images.githubusercontent.com/71936508/106365396-40657080-632d-11eb-8716-6fb25bfebf33.JPG)
![Capture](https://user-images.githubusercontent.com/71936508/106365366-0c8a4b00-632d-11eb-8cb5-8f438eaeb88c.JPG)

**Comment by babyraging** [comment] 2021-01-30 20:12
Hi there, thank you for the issue.

I see, the problem is caused by the file extension, e.g. `.lex`. By changing the file extension from `.lex` to `.l`, it should be working correctly.

According to the https://www.gnu.org/software/automake/manual/html_node/Yacc-and-Lex.html, `.lex` might not be a valid extension for lex source files.

**Comment by babyraging** [comment] 2021-03-15 21:51
I'm closing this issue since it can be resolved by using the above method.
Feel free to reopen if you have further questions.

**Closed by babyraging** 2021-03-15 21:51 UTC
